[build]
  publish = "dist/hscout"
  command = "ng build --aot"
# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
